### PR TITLE
Adding features

### PR DESCRIPTION
**Pull request by SimbaWANGU**
Added the following features
1. Added more description to the readme file
2. Added eslint for html and css to project
3. Added hello-microverse.html file
4. Added hello-microverse.css file
5. Added test.md file and ensured git ignores it in the .gitignore file

### CODE REVIEW

**Review by ShadyShawkat — CHANGES_REQUESTED** [review]
## Hi @S-imba, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

Image

## Required Changes ♻️
- [x] Please be sure that all linters pass correctly with green check marks. You can check what causes the linters error on GitHub and manually fix them in a new commit.

## Optional suggestions

- [ ] [OPTIONAL] Please make sure to give the feature branch a descriptive title in the feature, as an example you can call this branch "Set up Project" or something similar.
- [ ] [OPTIONAL] Kindly make sure to start your commits with present tense. So instead of writing "Added...", you write "Add...". This is a general commit naming convention.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SimbaWANGU** [comment]
Hi again @ShadyShawkat 
Done making the changes, kindly review my project and give me feedback

**Comment by ShadyShawkat** [comment]
Hi @S-imba,
Thank you for making the requested changes. Please go ahead and resubmit the project for a review.

**Review by ShadyShawkat — APPROVED** [review]
## Hi @S-imba, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by SimbaWANGU** [comment]
Thank you so much for the help @ShadyShawkat

**Pull request merged**
